[versions]
slf4j = "2.0.17"
log4j = "2.25.0"

annotations = "26.0.2"
lombok = "1.18.38"

okhttp = "5.1.0"
gson = "2.13.1"
databind = "2.19.1"

[libraries]
# Logging
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-sl4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }

# Code quality
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp" , version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "databind" }

[bundles]
logging = ["slf4j", "log4j-api", "log4j-core", "log4j-sl4j-impl"]
utils = ["annotations", "lombok"]